//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlinanUrunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlinanUrunler()
        {
            this.AlinanUrunFisleri = new HashSet<AlinanUrunFisleri>();
            this.Tedarikciler = new HashSet<Tedarikciler>();
        }
    
        public int AlinanUrunlerID { get; set; }
        public string AlinanUrunAdi { get; set; }
        public string AlinanUrunMarkasi { get; set; }
        public string AlinanUrunTuru { get; set; }
        public string AlinanUrunTipi { get; set; }
        public decimal AlinanUrunMiktari { get; set; }
        public string AlinanUrunPaketlemeTipi { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanUrunFisleri> AlinanUrunFisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tedarikciler> Tedarikciler { get; set; }
    }
}
