//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemekSiparisDBEntities : DbContext
    {
        public YemekSiparisDBEntities()
            : base("name=YemekSiparisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresler> Adresler { get; set; }
        public virtual DbSet<AlinanUrunFisleri> AlinanUrunFisleri { get; set; }
        public virtual DbSet<AlinanUrunler> AlinanUrunler { get; set; }
        public virtual DbSet<Fiyatlar> Fiyatlar { get; set; }
        public virtual DbSet<Ilceler> Ilceler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Kuryeler> Kuryeler { get; set; }
        public virtual DbSet<MenuDetay> MenuDetay { get; set; }
        public virtual DbSet<Menuler> Menuler { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<Sehirler> Sehirler { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Subeler> Subeler { get; set; }
        public virtual DbSet<SubeYemekleri> SubeYemekleri { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tedarikciler> Tedarikciler { get; set; }
        public virtual DbSet<YemekKatagorileri> YemekKatagorileri { get; set; }
        public virtual DbSet<Yemekler> Yemekler { get; set; }
        public virtual DbSet<YemekResimleri> YemekResimleri { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
        public virtual DbSet<Iadeler> Iadeler { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<Zaiyatlar> Zaiyatlar { get; set; }
    }
}
