//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personeller()
        {
            this.Kullanicilar = new HashSet<Kullanicilar>();
            this.Kuryeler = new HashSet<Kuryeler>();
            this.Siparisler = new HashSet<Siparisler>();
            this.Zaiyatlar = new HashSet<Zaiyatlar>();
        }
    
        public int PersonellerID { get; set; }
        public string PersonelAdi { get; set; }
        public string PersonelSoyadi { get; set; }
        public string PersonelTelefon { get; set; }
        public string PersonelEMail { get; set; }
        public string PersonelAdresi { get; set; }
        public System.DateTime PersonelDogumTarihi { get; set; }
        public string PersonelCinsiyeti { get; set; }
        public string PersonelPozisyonu { get; set; }
        public System.DateTime PersonelIseBaslamaTarihi { get; set; }
        public Nullable<System.DateTime> PersonelCikisTarihi { get; set; }
        public string PersonelEgitimi { get; set; }
        public decimal PersonelMaasi { get; set; }
        public byte[] PersonelFotografi { get; set; }
        public int SubeID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanicilar> Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kuryeler> Kuryeler { get; set; }
        public virtual Subeler Subeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaiyatlar> Zaiyatlar { get; set; }
    }
}
