//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparisler()
        {
            this.Iadeler = new HashSet<Iadeler>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.Zaiyatlar = new HashSet<Zaiyatlar>();
        }
    
        public int SiparislerID { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> AdresID { get; set; }
        public Nullable<int> KuryeID { get; set; }
        public int SubeID { get; set; }
        public Nullable<int> AdisonPersonelID { get; set; }
        public Nullable<decimal> OdenenTutar { get; set; }
    
        public virtual Adresler Adresler { get; set; }
        public virtual Kuryeler Kuryeler { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        public virtual Personeller Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iadeler> Iadeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        public virtual Subeler Subeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaiyatlar> Zaiyatlar { get; set; }
    }
}
