//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subeler()
        {
            this.AlinanUrunFisleri = new HashSet<AlinanUrunFisleri>();
            this.Personeller = new HashSet<Personeller>();
            this.Siparisler = new HashSet<Siparisler>();
            this.SubeYemekleri = new HashSet<SubeYemekleri>();
        }
    
        public int SubelerID { get; set; }
        public string SubeAdi { get; set; }
        public string SubeTelefon { get; set; }
        public string SubeAdres { get; set; }
        public int SubeIlceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanUrunFisleri> AlinanUrunFisleri { get; set; }
        public virtual Ilceler Ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personeller> Personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubeYemekleri> SubeYemekleri { get; set; }
    }
}
