//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tedarikciler()
        {
            this.AlinanUrunFisleri = new HashSet<AlinanUrunFisleri>();
        }
    
        public int TedarikciID { get; set; }
        public int UrunID { get; set; }
        public string TedarikciAdi { get; set; }
        public string IsletmeTuru { get; set; }
        public string TedarikciAdres { get; set; }
        public string TedarikciTelefonNo { get; set; }
        public string TedarikciEmail { get; set; }
        public bool TedarikciAktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlinanUrunFisleri> AlinanUrunFisleri { get; set; }
        public virtual AlinanUrunler AlinanUrunler { get; set; }
    }
}
