//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yemekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Yemekler()
        {
            this.Fiyatlar = new HashSet<Fiyatlar>();
            this.MenuDetay = new HashSet<MenuDetay>();
            this.SubeYemekleri = new HashSet<SubeYemekleri>();
            this.Iadeler = new HashSet<Iadeler>();
            this.SiparisDetay = new HashSet<SiparisDetay>();
            this.YemekResimleri = new HashSet<YemekResimleri>();
            this.Zaiyatlar = new HashSet<Zaiyatlar>();
        }
    
        public int YemeklerID { get; set; }
        public int KategoriID { get; set; }
        public string YemekAdi { get; set; }
        public string YemekIcerigi { get; set; }
        public string YemekAciklamasi { get; set; }
        public string KaloriBilgisi { get; set; }
        public decimal HazirlanmaSuresi { get; set; }
        public string PorsiyonBoyutu { get; set; }
        public System.DateTime AktiflikTarihi { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fiyatlar> Fiyatlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuDetay> MenuDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubeYemekleri> SubeYemekleri { get; set; }
        public virtual YemekKatagorileri YemekKatagorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Iadeler> Iadeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YemekResimleri> YemekResimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaiyatlar> Zaiyatlar { get; set; }
    }
}
