//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekSiparis.DLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekResimleri
    {
        public int YemekResimleriID { get; set; }
        public string ResimAdi { get; set; }
        public string ResimYolu { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public int YemekID { get; set; }
        public int AktifMi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Yemekler Yemekler { get; set; }
    }
}
